### ISSUE TITLE
向您请教

### ISSUE THREAD

**Issue by gz-sky** [caoqianming/django-vue-admin#11]
您好,已star,下载运行后发现,新增加用户时,不知道该用户的密码是多少 可否告知一下

**Comment by caoqianming** [comment]
0000，userviewset代码里有写，可以看一下



---原始邮件---
发件人: "gz-sky"<notifications@github.com&gt;
发送时间: 2020年12月8日(周二) 上午10:12
收件人: "caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [caoqianming/django-vue-admin] 向您请教 (#11)




 
您好,已star,下载运行后发现,新增加用户时,不知道该用户的密码是多少 可否告知一下

**Comment by gz-sky** [comment]
感谢 感谢
