### ISSUE TITLE
您好，想问一下接口的设计情况

### ISSUE THREAD

**Issue by fjl-gj** [caoqianming/django-vue-admin#12]
抱歉打扰了，但是还是想请教您一下
关于这套模板里面的前后端数据接口
![image](https://user-images.githubusercontent.com/45162887/101601021-18e1de00-3a37-11eb-8e01-3ef08ec2c41a.png)
![image](https://user-images.githubusercontent.com/45162887/101601078-2f883500-3a37-11eb-8ce4-54c8bd596e82.png)
![image](https://user-images.githubusercontent.com/45162887/101601152-4c246d00-3a37-11eb-9c2a-f8ce2f21f0b6.png)
咨询一下关于接口的设计情况，动态拿到权限然后做侧边栏的筛选
基于初始化data用户信息，做的接口设计拿到perms权限，但是我在测试的时候，发现并不是很明确，想请教您

**Comment by fjl-gj** [comment]
不好意思，我看到了db.json格式，了解到了具体情况。

**Comment by caoqianming** [comment]
具体什么问题呢



---原始邮件---
发件人: "Chris"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 下午4:00
收件人: "caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [caoqianming/django-vue-admin] 您好，想问一下接口的设计情况 (#12)




 
抱歉打扰了，但是还是想请教您一下
 关于这套模板里面的前后端数据接口
 
 
 
 咨询一下关于接口的设计情况，动态拿到权限然后做侧边栏的筛选
 基于初始化data用户信息，做的接口设计拿到perms权限，但是我在测试的时候，发现并不是很明确，想请教您
