### ISSUE TITLE
此项目特别有价值，请问简易的工作流模块 计划什么时候？

### ISSUE THREAD

**Issue by weijie199148** [caoqianming/django-vue-admin#13]
此项目特别有价值，请问简易的工作流模块 计划什么时候？

**Comment by caoqianming** [comment]
谢谢,我也不好说有时间就会弄上去,主要是想参考loonflow,您可以看看。不过不会搞他那样全面，我觉得满足基本的工作流就行，复杂的还得单独写




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caoqianming/django-vue-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 下午3:17
收件人:&nbsp;"caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[caoqianming/django-vue-admin] 此项目特别有价值，请问简易的工作流模块 计划什么时候？ (#13)





 
此项目特别有价值，请问简易的工作流模块 计划什么时候？

**Comment by weijie199148** [comment]
十分感谢您
