### ISSUE TITLE
跑不起来啊，老大能在详细吗，还要用redis？

### ISSUE THREAD

**Issue by bergkamp2008999** [caoqianming/django-vue-admin#14]

**Comment by caoqianming** [comment]
redis不是必要的。提供报错图



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bergkamp2008999"<notifications@github.com&gt;; 
发送时间: 2021年1月14日(星期四) 上午10:02
收件人: "caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [caoqianming/django-vue-admin] 跑不起来啊，老大能在详细吗，还要用redis？ (#14)

**Comment by bergkamp2008999** [comment]
<img width="740" alt="1610598881(1)" src="https://user-images.githubusercontent.com/7258123/104545490-222d1e80-5665-11eb-9323-2e44cbd49ef5.png">
<img width="564" alt="1610598903(1)" src="https://user-images.githubusercontent.com/7258123/104545491-25280f00-5665-11eb-8c78-6103bafa4e7c.png">
写了redis地址后可以运行了。

**Comment by bergkamp2008999** [comment]
<img width="740" alt="1610598881(1)" src="https://user-images.githubusercontent.com/7258123/104545551-4ee13600-5665-11eb-8b86-5a2d23941487.png">
