### ISSUE TITLE
新添加菜单，分配完角色权限后显示不出来

### ISSUE THREAD

**Issue by bergkamp2008999** [caoqianming/django-vue-admin#16]
没有报错信息

**Comment by bergkamp2008999** [comment]
<img width="316" alt="1610680133(1)" src="https://user-images.githubusercontent.com/7258123/104676339-266b4180-5722-11eb-80ad-be66d13661a4.png">
左侧的菜单是静态的吧，改名字也不变更。

**Comment by caoqianming** [comment]
前端router要写一下啊



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bergkamp2008999"<notifications@github.com&gt;; 
发送时间: 2021年1月15日(星期五) 上午10:51
收件人: "caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [caoqianming/django-vue-admin] 新添加菜单，分配完角色权限后显示不出来 (#16)





 
没有报错信息

**Comment by caoqianming** [comment]
用的是前端路由模式




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caoqianming/django-vue-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 上午10:51
收件人:&nbsp;"caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[caoqianming/django-vue-admin] 新添加菜单，分配完角色权限后显示不出来 (#16)





 
没有报错信息

**Comment by bergkamp2008999** [comment]
就是是静态的？路由怎么改下呢？

**Comment by caoqianming** [comment]
这样，你先去看看vue element admin， 了解一下前端路由模式



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bergkamp2008999"<notifications@github.com&gt;; 
发送时间: 2021年1月15日(星期五) 中午11:11
收件人: "caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;; 
抄送: "caoqia"<909355014@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [caoqianming/django-vue-admin] 新添加菜单，分配完角色权限后显示不出来 (#16)





 
就是是静态的？路由怎么改下呢？

**Comment by bergkamp2008999** [comment]
component: () => import('@/views/system/dict'),
        meta: { title: '数据字典', icon: 'example', perms: ['dict_manage'] }
就是需要写页面里面，然后再判断权限是吧

**Comment by bergkamp2008999** [comment]
就是不新增，我把接口文档菜单权限取消，也没效果的，老兄

**Comment by caoqianming** [comment]
对




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bergkamp2008999"<notifications@github.com&gt;; 
发送时间: 2021年1月15日(星期五) 中午11:15
收件人: "caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;; 
抄送: "caoqia"<909355014@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [caoqianming/django-vue-admin] 新添加菜单，分配完角色权限后显示不出来 (#16)





     component: () =&gt; import('@/views/system/dict'),     meta: { title: '数据字典', icon: 'example', perms: ['dict_manage'] }  
就是需要写页面里面，然后再判断权限是吧

**Comment by caoqianming** [comment]
接口文档那个没写控权吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bergkamp2008999"<notifications@github.com&gt;; 
发送时间: 2021年1月15日(星期五) 中午11:21
收件人: "caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;; 
抄送: "caoqia"<909355014@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [caoqianming/django-vue-admin] 新添加菜单，分配完角色权限后显示不出来 (#16)





 
就是不新增，我把接口文档菜单权限取消，也没效果的，老兄

**Comment by caoqianming** [comment]
修改权限后最好重新登陆，写了有信号，但最好还是重新登陆




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caoqianming/django-vue-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 中午11:21
收件人:&nbsp;"caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;;
抄送:&nbsp;"caoqia"<909355014@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [caoqianming/django-vue-admin] 新添加菜单，分配完角色权限后显示不出来 (#16)





 
就是不新增，我把接口文档菜单权限取消，也没效果的，老兄

**Comment by bergkamp2008999** [comment]
可以了
