### ISSUE TITLE
关于一些操作问题，不知道怎么弄得，所以咨询一下作者大佬

### ISSUE THREAD

**Issue by sky508** [caoqianming/django-vue-admin#19]
![image](https://user-images.githubusercontent.com/26371416/108586164-a0c55c00-7387-11eb-9ac6-01e3f8c44dc4.png)
请问这个为什么直接就可以进行增删查改呀？是使用什么原理的？

**Comment by caoqianming** [comment]
这个是drf的封装，你可以看看它的文档
