### ISSUE TITLE
目录改的pycharm无法直接启动服务

### ISSUE THREAD

**Issue by godzeo** [caoqianming/django-vue-admin#21]
这个目录结构不知道这么，pycharm已经无法识别，，只能命令后启动
![image](https://user-images.githubusercontent.com/64398024/110056801-6ce03280-7d9a-11eb-80d7-9d2c95605233.png)
![image](https://user-images.githubusercontent.com/64398024/110056833-779ac780-7d9a-11eb-9a77-e431fba6302c.png)

**Comment by caoqianming** [comment]
我也不太清楚哎,我用vscode

**Comment by RunningFaster** [comment]
Pycharm
**Debug**正常启动成功，没有遇到问题，检查一下你的项目文件夹路径或者环境是否对应
