### ISSUE TITLE
用的都是什么环境呢，前端npm install报错

### ISSUE THREAD

**Issue by wangxianbiao** [caoqianming/django-vue-admin#22]
![image](https://user-images.githubusercontent.com/43992814/111593139-9a01fb80-8804-11eb-999e-fe5312b4c4fa.png)

**Comment by caoqianming** [comment]
升级下node版本，应该node sass就不会报错了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午4:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [caoqianming/django-vue-admin] 用的都是什么环境呢，前端npm install报错 (#22)

**Comment by wangxianbiao** [comment]
> 升级下node版本，应该node sass就不会报错了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月18日(星期四) 下午4:12 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [caoqianming/django-vue-admin] 用的都是什么环境呢，前端npm install报错 (#22) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

更新到14.16.0还不行，需要升到15嘛

**Comment by wangxianbiao** [comment]
> > 升级下node版本，应该node sass就不会报错了
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2021年3月18日(星期四) 下午4:12 收件人: _**@**_.**_>; 抄送: _**@**_.***>; 主题: [caoqianming/django-vue-admin] 用的都是什么环境呢，前端npm install报错 (#22) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 更新到14.16.0还不行，需要升到15嘛，你们用的是哪个版本呢

构建client项目换成python2环境可以了

**Comment by caoqianming** [comment]
不是吧。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月19日(星期五) 中午11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [caoqianming/django-vue-admin] 用的都是什么环境呢，前端npm install报错 (#22)





   
升级下node版本，应该node sass就不会报错了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年3月18日(星期四) 下午4:12 收件人: _@**._&gt;; 抄送: _@_.*&gt;; 主题: [caoqianming/django-vue-admin] 用的都是什么环境呢，前端npm install报错 (#22) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
更新到14.16.0还不行，需要升到15嘛，你们用的是哪个版本呢
  
构建client项目换成python2环境可以了

**Comment by TheBloodthirster** [comment]
> 



> > > 升级下node版本，应该node sass就不会报错了
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2021年3月18日(星期四) 下午4:12 收件人: _**@**_.**_>; 抄送: _**@**_.***>; 主题: [caoqianming/django-vue-admin] 用的都是什么环境呢，前端npm install报错 (#22) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 更新到14.16.0还不行，需要升到15嘛，你们用的是哪个版本呢
> 
> 构建client项目换成python2环境可以了

楼主，意思是说

npm install --registry=https://registry.npm.taobao.org

这里换成python2环境安装编译client项目么，本机环境python3这一步出错了。
感谢楼主分享项目

**Comment by wangxianbiao** [comment]
> > 
> 
> > > > 升级下node版本，应该node sass就不会报错了
> > > > […](#)
> > > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2021年3月18日(星期四) 下午4:12 收件人: _**@**_.**_>; 抄送: _**@**_.***>; 主题: [caoqianming/django-vue-admin] 用的都是什么环境呢，前端npm install报错 (#22) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 更新到14.16.0还不行，需要升到15嘛，你们用的是哪个版本呢
> > 
> > 
> > 构建client项目换成python2环境可以了
> 
> 楼主，意思是说
> 
> npm install --registry=https://registry.npm.taobao.org
> 
> 这里换成python2环境安装编译client项目么，本机环境python3这一步出错了。 感谢楼主分享项目

是的，我环境变量改成python2就可以了。看报错日志是python2的语法
