### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by a-bo** [caoqianming/django-vue-admin#25]
Error: PostCSS plugin autoprefixer requires PostCSS 8. Update PostCSS or downgrade this plugin.

**Comment by caoqianming** [comment]
升级一下node呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月28日(周五) 上午10:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [caoqianming/django-vue-admin] npm run dev 报错 (#25)




 
Error: PostCSS plugin autoprefixer requires PostCSS 8. Update PostCSS or downgrade this plugin.

**Comment by a-bo** [comment]
node 的版本 v14.17.0
降低了autoprefixer版本解决： npm -i postcss-loader autoprefixer@8.0.0 -D

**Comment by caoqianming** [comment]
嗯




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月1日(星期二) 下午4:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [caoqianming/django-vue-admin] npm run dev 报错 (#25)





 
node 的版本 v14.17.0
 降低了autoprefixer版本解决： npm -i postcss-loader ***@***.*** -D
