### ISSUE TITLE
请问岗位管理这个页面有什么作用呢，没太搞懂

### ISSUE THREAD

**Issue by lqs429521992** [caoqianming/django-vue-admin#3]
我看到其他项目也有，但不知道为什么，求解答~

**Comment by caoqianming** [comment]
嗯，这个问题我我也想过。很多时候岗位和角色是有交叉地的，事实上我有的系统直接就统一到一起，但是后来发现也不太合适。另外也不好放到数据字典里。总之，岗位是现实生活中比较重要的概念，跟业务也是很相关的，所以具体到实现中，你可以根据情况自己加字段。

**Comment by kingctan** [comment]
这个机构，可以理解为组。 在权限模型中，有用户权限，用户组权限，用户角色权限，

组权限，可以是不同角色的用户，创建一个组，再给这个组建一个权限。

**Comment by FengGuanxi** [comment]
没有看到要怎么通过角色来限制功能的步骤介绍，不太理解到底应该如何使用
