### ISSUE TITLE
头像无法加载

### ISSUE THREAD

**Issue by MingJ-Zhang** [caoqianming/django-vue-admin#30]
头像无法加载

**Comment by caoqianming** [comment]
看看nginx 配置



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 下午2:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [caoqianming/django-vue-admin] 头像无法加载 (#30)





 
头像无法加载

**Comment by caoqianming** [comment]
ok
