### ISSUE TITLE
请问mac 电脑运行报错

### ISSUE THREAD

**Issue by rockmelodies** [caoqianming/django-vue-admin#4]
![image](https://user-images.githubusercontent.com/24653177/91812306-6d6d0480-ec63-11ea-9288-cead5e481d40.png)

**Comment by caoqianming** [comment]
在server下建一个log文件夹

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/91812881-5ed31d00-ec64-11ea-9add-19b1ffb24d35.png)
建了还是报错
![image](https://user-images.githubusercontent.com/24653177/91812924-73171a00-ec64-11ea-8b54-edc0f076fe03.png)

**Comment by caoqianming** [comment]
建错位置了，与manage.py同一个文件夹。用来存放日志的，还需要建一个media文件夹

**Comment by rockmelodies** [comment]
npm node 版本有啥要求吗
