### ISSUE TITLE
软删除了之后查不出状态is_deleted=True的数据

### ISSUE THREAD

**Issue by lilue** [caoqianming/django-vue-admin#42]
model.objects.filter(is_deleted=True)是空的。这个该怎么查？

**Comment by caoqianming** [comment]
您好，目前可以这样做；model.objects.get_queryset(all=True).filter(is_deleted=True); 后面可以优化一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月21日(星期五) 上午9:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [caoqianming/django-vue-admin] 软删除了之后查不出状态is_deleted=True的数据 (Issue #42)





 
model.objects.filter(is_deleted=True)是空的。这个该怎么查？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lilue** [comment]
我现在是想all()查出所有数据，取最新数据的number + 1 给新增的记录。软删除后all()查出来的数据只有未删除的。我试试你说的这个。
