### ISSUE TITLE
自述文件提供的用户名密码是错误的。

### ISSUE THREAD

**Issue by BeHappy0o0o0o0** [caoqianming/django-vue-admin#43]
如题：

**Comment by ldsxp** [comment]
可能使用的数据库不对，用 manage.py createsuperuser  命令创建一个新得管理员。

**Comment by BeHappy0o0o0o0** [comment]
好的，谢谢.


在 2022年1月27日，23:21，ldsxp ***@***.***> 写道：

﻿

可能使用的数据库不对，用 manage.py createsuperuser 命令创建一个新得管理员。

**Comment by caoqianming** [comment]
嗯，应该是被修改了，我处理一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月27日(星期四) 晚上11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [caoqianming/django-vue-admin] 自述文件提供的用户名密码是错误的。 (Issue #43)





 
如题：
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
