### ISSUE TITLE
您好 刚才在部署运行项目时，发现用户管理-新增用户-点击确认时出现 phone:该字段是必填项。可否帮忙解决一下，感谢感谢

### ISSUE THREAD

**Issue by wangguangzhong** [caoqianming/django-vue-admin#45]
![image](https://user-images.githubusercontent.com/28469601/155284622-7545083c-a123-4224-abec-2ca92f20090d.png)

**Comment by caoqianming** [comment]
这样改一下即可

phone = serializers.CharField(max_length=11, required=False)





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月23日(星期三) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [caoqianming/django-vue-admin] 您好 刚才在部署运行项目时，发现用户管理-新增用户-点击确认时出现 phone:该字段是必填项。可否帮忙解决一下，感谢感谢 (Issue #45)





 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangguangzhong** [comment]
> 这样改一下即可 phone = serializers.CharField(max_length=11, required=False)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年2月23日(星期三) 下午4:33 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [caoqianming/django-vue-admin] 您好 刚才在部署运行项目时，发现用户管理-新增用户-点击确认时出现 phone:该字段是必填项。可否帮忙解决一下，感谢感谢 (Issue #45) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢感谢 已经可以了
