### ISSUE TITLE
'ManyRelatedManager' object has no attribute 'depts'

### ISSUE THREAD

**Issue by xyuer** [caoqianming/django-vue-admin#46]
https://github.com/caoqianming/django-vue-admin/blob/5ecb707377fe174ae1c59423920657d46185c5fa/server/apps/system/permission_data.py#L43

if roles.depts.exists(): 这里是不是不能这样写？

**Comment by caoqianming** [comment]
可以的。因为定义了roles这个manytomanyfield



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月25日(星期五) 晚上8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [caoqianming/django-vue-admin] &#39;ManyRelatedManager&#39; object has no attribute &#39;depts&#39; (Issue #46)





 
https://github.com/caoqianming/django-vue-admin/blob/5ecb707377fe174ae1c59423920657d46185c5fa/server/apps/system/permission_data.py#L43
 
if roles.depts.exists(): 这里是不是不能这样写？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caoqianming** [comment]
不好意思我好像回错了，我看一下

**Comment by caoqianming** [comment]
修改了，现在是
`depts = models.ManyToManyField(
        Organization, blank=True, verbose_name='权限范围', related_name='roles')`
然后
`queryset = queryset.filter(belong_dept__roles__in=roles)`

**Comment by xyuer** [comment]
https://github.com/caoqianming/django-vue-admin/blob/a0fa9437ec66374982ad8923f49cc52f2393c63f/server/apps/system/permission.py#L82

这里也要改

**Comment by caoqianming** [comment]
谢谢。已经改了

**Comment by xyuer** [comment]
https://github.com/caoqianming/django-vue-admin/blob/8a9efbbbd1e7771249f938394795c23b7f1ab851/server/apps/system/permission.py#L82
depts = Organization.objects.filter(roles__in = roles) 这里要改成roles.all()
