### ISSUE TITLE
python 3.6 don't support djangorestframework-simplejwt==4.7.2

### ISSUE THREAD

**Issue by Laurel-rao** [caoqianming/django-vue-admin#47]

**Comment by caoqianming** [comment]
升级一下到python3.8；或者降低simplejwt，可看下其文档降到多少比较合适



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月28日(星期一) 上午10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [caoqianming/django-vue-admin] python 3.6 don&#39;t support djangorestframework-simplejwt==4.7.2 (Issue #47)

**Comment by Laurel-rao** [comment]
改成 4.4.0 之后提示return token.decode(‘utf-8’) 报错， 改成 return token 去掉 decode就好了
