### ISSUE TITLE
mysql verison >8.0  because use format json

### ISSUE THREAD

**Issue by Laurel-rao** [caoqianming/django-vue-admin#48]

**Comment by Laurel-rao** [comment]
新增不需要 phone_number 修改提示phone_number 不能为空

**Comment by caoqianming** [comment]
修改一下serializer即可，我回头改一下



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 28, 2022 11:38 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [caoqianming/django-vue-admin] mysql verison &gt;8.0  because useformat json (Issue #48)




 
新增不需要 phone_number 修改提示phone_number 不能为空

**Comment by caoqianming** [comment]
线上展示的那个我一直没更新过



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 28, 2022 11:38 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [caoqianming/django-vue-admin] mysql verison &gt;8.0  because useformat json (Issue #48)




 
新增不需要 phone_number 修改提示phone_number 不能为空
