### ISSUE TITLE
请问图像加载不出来 怎没处理 呢 请求的img type 是text/html

### ISSUE THREAD

**Issue by 1353644643** [caoqianming/django-vue-admin#5]
![image](https://user-images.githubusercontent.com/51155899/94246014-b86df500-ff4d-11ea-93c9-afaaa6fcfeb5.png)
![image](https://user-images.githubusercontent.com/51155899/94246272-1f8ba980-ff4e-11ea-9d33-c342484660b9.png)

**Comment by caoqianming** [comment]
自己在media下加一个default文件夹，放一个avatar.png。

**Comment by caoqianming** [comment]
或者重新编辑一下用户，上传自己的图片

**Comment by 1353644643** [comment]
这个我试过了 不行呀  
![image](https://user-images.githubusercontent.com/51155899/94256442-67193200-ff5c-11ea-9fe8-5d9e63ab17f9.png)

**Comment by caoqianming** [comment]
原来是permission_classes=[IsAuthenticated]没加，我没注意到，额
