### ISSUE TITLE
预览地址账号密码无效

### ISSUE THREAD

**Issue by hxm-666** [caoqianming/django-vue-admin#51]

**Comment by caoqianming** [comment]
重置了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caoqianming/django-vue-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月13日(星期五) 下午3:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[caoqianming/django-vue-admin] 预览地址账号密码无效 (Issue #51)

**Comment by hxm-666** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 下午3:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [caoqianming/django-vue-admin] 预览地址账号密码无效 (Issue #51)





 重置了 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "caoqianming/django-vue-admin"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年5月13日(星期五) 下午3:10 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[caoqianming/django-vue-admin] 预览地址账号密码无效 (Issue #51)
