### ISSUE TITLE
关于权限认证

### ISSUE THREAD

**Issue by lekeeith** [caoqianming/django-vue-admin#6]
你好，你这个权限是不是没有完善？
我建立一个角色--测试角色，没有给测试角色打开/user/role的权限，但实测可以打开。
这个不能上传图片，，，，

**Comment by lekeeith** [comment]
还有数据字典有啥用呢？

**Comment by caoqianming** [comment]
哦，有些按钮权限标识没写到前端，已经改了。数据字典是做管理系统用的，
图片问题上传提示无权限，已修改




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lekeeith"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 下午2:35
收件人: "caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [caoqianming/django-vue-admin] 关于权限认证 (#6)





 
你好，你这个权限是不是没有完善？
 我建立一个角色--测试角色，没有给测试角色打开/user/role的权限，但实测可以打开。
 这个不能上传图片，，，，

**Comment by lekeeith** [comment]
不是，是权限没有起作用。我没有给sherr用户权限，但是postman依旧可以访问。

**Comment by caoqianming** [comment]
role的get权限是放开的，自己可以修改







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lekeeith"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 下午3:29
收件人: "caoqianming/django-vue-admin"<django-vue-admin@noreply.github.com&gt;; 
抄送: "caoqia"<909355014@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [caoqianming/django-vue-admin] 关于权限认证 (#6)





 
不是，是权限没有起作用。我没有给sherr用户权限，但是postman依旧可以访问。

**Comment by lekeeith** [comment]
了解，谢谢了！
