### ISSUE TITLE
关于周期性任务

### ISSUE THREAD

**Issue by lilue** [caoqianming/django-vue-admin#60]
关于定时任务
使用celery以及django_celery_beat包实现

需要安装redis并在默认端口启动, 并启动worker以及beat

进入虚拟环境并启动worker: celery -A server worker -l info -P eventlet, linux系统不用加-P eventlet

进入虚拟环境并启动beat: celery -A server beat -l info

我注册了任务，配置了周期性任务每分钟运行，但是就是没能成功运行，不知道是哪里的问题。
worker和beat都启动了，手动触发show就能执行。
能麻烦解答一下吗
感谢

**Comment by caoqianming** [comment]
可以安装django celery results包，在admin后台看看执行状态



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月29日(周三) 晚上6:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [caoqianming/django-vue-admin] 关于周期性任务 (Issue #60)




 
关于定时任务
 使用celery以及django_celery_beat包实现
 
需要安装redis并在默认端口启动, 并启动worker以及beat
 
进入虚拟环境并启动worker: celery -A server worker -l info -P eventlet, linux系统不用加-P eventlet
 
进入虚拟环境并启动beat: celery -A server beat -l info
 
我注册了任务，配置了周期性任务每分钟运行，但是就是没能成功运行，不知道是哪里的问题。
 worker和beat都启动了，手动触发show就能执行。
 能麻烦解答一下吗
 感谢

**Comment by lilue** [comment]
django celery results我有装了，问题是好像beat没把任务挂上去，并没有执行。但是我用django shell手动设置show异步又能执行， celery results表记录成功。只在admin后台配置了周期任务，每分钟执行一次，等了好几分钟都没反应，没报错、没执行。我明天再试下直接在setting里设置看看。CELERY_BEAT_SCHEDULE = {
    'celery4_text': { # 任务名(随意起)
        'task': 'app.tasks.text', # 定时任务函数路径
        'schedule': timedelta(seconds=30), # 任务循环时间
        "args": (4,9), # 参数
},

**Comment by lilue** [comment]
把任务在settings里设置CELERY_BEAT_SCHEDULE能成功触发，加在数据库不行，没找到愿意- -

**Comment by lilue** [comment]
有加，加了这个和没加这个都试过。直接down你的项目运行也没成功

**Comment by caoqianming** [comment]
稍等我更新一下包

**Comment by lilue** [comment]
我先按着在settings里配置了。不知道老哥做没做过打印，我有个功能不知道怎么实现，就是现在我有一个模板文件，Excel或者word格式都行，我想读取模板文件后替换文件中的占位符，然后设置A5大小的打印。我查了半天找不到该怎么做，老哥方便指点一下吗？

**Comment by caoqianming** [comment]
用docxtpl

**Comment by mocehu** [comment]
怎么解决的，我也遇到了，有时候正常执行，有时候不执行
