### ISSUE TITLE
python manage.py runserver

### ISSUE THREAD

**Issue by 20chenweilong** [caoqianming/django-vue-admin#61]
运行时说找不到index.html:django.template.exceptions.TemplateDoesNotExist: index.html

**Comment by 20chenweilong** [comment]
![图片](https://user-images.githubusercontent.com/116883110/229055857-f4066821-c297-4c38-9285-48885d9cff02.png)

**Comment by caoqianming** [comment]
用node16吧，先安装包npm install



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 31, 2023 15:40 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [caoqianming/django-vue-admin] python manage.py runserver (Issue#61)
