### ISSUE TITLE
关于菜单颜色

### ISSUE THREAD

**Issue by lilue** [caoqianming/django-vue-admin#62]
我现在有个地方自己不会处理，就是菜单颜色，代码里是读取的variables.scss配置的颜色，我现在想改成在编译的时候通过我传入的参数设置颜色，我看element ui的菜单是有默认颜色和自定义颜色嘛，我现在就想有个这么的设置，比如我在.env.production里添加一个参数，在编译的时候通过这个参数判断是用默认的菜单颜色或者是自定义颜色，这个该怎么弄呢，scss这种我不太不会弄，我同一套代码想通过颜色区分开，部署了两个项目。

**Comment by caoqianming** [comment]
你好，你可以看看其他前端项目里关于这块怎么处理的。我帮你问了gpt

如果你想在 SCSS 中使用环境变量，可以通过 sass-loader 来实现。

首先，在 .env.production 文件中定义环境变量，例如：

arduino
Copy code
VUE_APP_CUSTOM_COLOR=true
然后，在 vue.config.js 中配置 sass-loader：

js
Copy code
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        additionalData: `
          $custom-color: ${process.env.VUE_APP_CUSTOM_COLOR === 'true' ? 'red' : 'green'};
        `
      }
    }
  }
}
在 SCSS 文件中，你可以使用 $custom-color 变量来引用自定义颜色：

scss
Copy code
.menu {
  background-color: $custom-color;
}
