### ISSUE TITLE
你好，问一个问题。

### ISSUE THREAD

**Issue by lekeeith** [caoqianming/django-vue-admin#7]
### 关于extra action的权限处理
作者你这个权限管理我有一点不清楚。在你的userviewset里面定义一个info，我该怎么做才能把info加到rbac里面呢？
```python
    # perms_map={'get':'*'}, 自定义action控权
    @action(methods=['get'], detail=False, url_name='my_info', permission_classes=[IsAuthenticated])
    def info(self, request, pk=None):
```
你的info加了一个permission，`permission_classes=[IsAuthenticated]`，这一点我也很清楚。不过怎么加到rbac里面呢？
### 关于cache
你把权限字典写在cache里面，但是更改权限时候并不是实时生效的（我自己测试是这个样子的），要不要加个信号保证cache里的数据实时更新呢？

**Comment by lekeeith** [comment]
## extra权限
emmm，我发现在@action后面可以加perms_map={'get':'xxx'},所以这个问题结束了。
我自己没有用信号机制，我是取消了cache，作者大大，你写一个信号呗。

**Comment by caoqianming** [comment]
嗯
1.将permission_classes去了，定义perms_map={'get':'my_info'}
2.可以重新登陆，回头加个信号
