### ISSUE TITLE
定时任务相关

### ISSUE THREAD

**Issue by yushouzi** [caoqianming/django-vue-admin#75]
定时任务中，定时任务每10秒执行一次，celery的日志显示也是执行成功的。但是以执行次数和最后执行时间却是3分钟更新一次，大佬这是什么原因？

**Comment by caoqianming** [comment]
先更新下django celery results包看看这个问题还会不会出现。

**Comment by caoqianming** [comment]
查了一下源码，是celery默认的更新策略 

![44PD7@EFN%@_2%LX5VL)`$1](https://github.com/caoqianming/django-vue-admin/assets/21101210/2c6857f5-b0f3-46d2-ba73-4309e6ce4bc6)

如果要实时更新到数据库继承一下django celery beat的databaseschedule 然后改了这个参数，然后在django setting里指定你的schedule
