### ISSUE TITLE
微信二维码过期了，能否更新一下

### ISSUE THREAD

**Issue by ChanXing2023** [caoqianming/django-vue-admin#77]

**Comment by caoqianming** [comment]
好了已更新

**Comment by ai408** [comment]
又过期了。

**Comment by caoqianming** [comment]
更新了，应该过一会github能反应过来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月25日(周四) 晚上9:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [caoqianming/django-vue-admin] 微信二维码过期了，能否更新一下 (Issue #77)




 
又过期了。
