### ISSUE TITLE
前端环境安装失败

### ISSUE THREAD

**Issue by zhangyupeng233** [caoqianming/django-vue-admin#80]
node版本: 16.20.2
npm版本: 8.19.4

问题描述

尝试1: 使用cnpm 安装  安装完成后启动失败  提示缺少chokidar  body-parser 等等一系列依赖, 安装失败

尝试2: 使用教程中的 npm install --registry=https://registry.npm.taobao.org  超时未响应

尝试3: 替换镜像地址  npm install --registry=https://registry.npmmirror.com/  安装中途报错推出  报错如下

**Comment by zhangyupeng233** [comment]
![微信截图_20240712094222](https://github.com/user-attachments/assets/6354d46d-e667-4587-a593-4725d9f9c904)

**Comment by caoqianming** [comment]
我这里的版本node 18.17.0  npm 10.0.0     你要不要升级到这个版本试一下

**Comment by zhangyupeng233** [comment]
> 我这里的版本node 18.17.0 npm 10.0.0 你要不要升级到这个版本试一下

请问下  vue-cli版本是多少

**Comment by caoqianming** [comment]
@vue/cli 5.0.8
