### ISSUE TITLE
请教如何自动发现路由

### ISSUE THREAD

**Issue by AndyHu888** [caoqianming/django-vue-admin#83]
刚刚学习drf，问一个比较初级的问题，想知道前后端分离来实现RBAC如何才能自动发现新增模块的路由（当程序添加了一个新的view，系统需要发现这个view的路由，系统管理员可以根据路由来输入路由的名称(如命名为新建采购单、编辑采购单、删除采购单。。。)），我的email是82581963@qq.com， 谢谢。

**Comment by caoqianming** [comment]
您好，是这样的。在该项目中后端写好接口后，需要自己手动录入到菜单管理那里，未提供自动生成到数据库的功能。如果需要自动生成的话，可以django setup或swagger init时做这个操作。

另外其实后端只需要提供权限标识，如何组织和显示菜单前端去控制即可。

另外为了更适应这种模式，我在base分支里权限标识字段我设置成可支持json，从而可以配置成下图所示

![image](https://github.com/user-attachments/assets/55d74c24-5d4f-4ef6-aed8-386483496074)

仅作参考
