### ISSUE TITLE
大佬，readme中npm taobao镜像超时不可用，请替换npmmirror

### ISSUE THREAD

**Issue by eitan-jan** [caoqianming/django-vue-admin#88]
亲测这个可用 npm install --registry=https://registry.npmmirror.com/

**Comment by eitan-jan** [comment]
大佬，看到再更新下群二维码，要不要搞个qq群啊？

**Comment by caoqianming** [comment]
好的。明天改一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月9日(周三) 晚上10:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [caoqianming/django-vue-admin] readme中npm taobao镜像超时不可用，请替换npmmirror (Issue #88)




 
亲测这个可用 npm install --registry=https://registry.npmmirror.com/

**Comment by caoqianming** [comment]
已换，二维码已更新
